# Generated by Django 5.0.1 on 2025-06-16 15:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='recipes_cat_name_0c4a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='recipes_cat_slug_178eca_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name'], name='recipes_ing_name_164c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['recipe'], name='recipes_ing_recipe__fac781_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['recipe', 'user'], name='recipes_rat_recipe__f4a8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['value'], name='recipes_rat_value_c02d67_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['created_at'], name='recipes_rat_created_462957_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['title'], name='recipes_rec_title_9ebae8_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['slug'], name='recipes_rec_slug_412256_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_at'], name='recipes_rec_created_a55f59_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_published'], name='recipes_rec_is_publ_8ba3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_featured'], name='recipes_rec_is_feat_75f06e_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['average_rating'], name='recipes_rec_average_07913b_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['views_count'], name='recipes_rec_views_c_97eb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty'], name='recipes_rec_difficu_33131c_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['cooking_time'], name='recipes_rec_cooking_bf57fb_idx'),
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['recipe', 'order'], name='recipes_ste_recipe__bd7ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='recipes_use_user_id_056acb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['location'], name='recipes_use_locatio_6ce82c_idx'),
        ),
    ]
