# Generated by Django 5.0.1 on 2025-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_remove_recipe_favorites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='recipes/images/default.jpg', null=True, upload_to='category_images/'),
        ),
    ]
